### PR TITLE
Translations data

### PR DESCRIPTION
**Pull request by sviridovs**
Title, overview and homepage in the translation object

### CODE REVIEW

**Comment by antunesl** [comment]
Hi, is there an alternative way to get tranlated data from the API instead of looking into data property of Translation, like it is done in this PR?

**Comment by LordMike** [comment]
I don't think so ? .. You can check the API docs to see if there is a way that suits you better. If TMDbLib doesn't support it, add an issue or open a PR to have it added.

**Comment by antunesl** [comment]
This PR adds that behavior, any reason why it can’t be merged? If there is, maybe I can help.

**Comment by LordMike** [comment]
Iirc I closed it because similar was already in place.

**Comment by LordMike** [comment]
Ah.. because TranslationWithCountry disappeared.

**Pull request closed without merging**
