### PR TITLE
Fixed issue #249 by renaming JobList to Jobs

### LINKED ISSUE #249: JsonProperty for Job object
Please check if this is correct

https://github.com/LordMike/TMDbLib/blob/049fba9f720acf21534ae8d2f4dca7a375586cb8/TMDbLib/Objects/General/Job.cs#L11

Shouldn't it be "jobs" instead of "job_list"?

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes #249

### CODE REVIEW

**Comment by LordMike** [comment]
Does it work?.. I can't find the documentation for `job/list` right now.

**Comment by FrederikBolding** [comment]
It fixed the test case 😄

**Comment by LordMike** [comment]
I mean, I can't find the API endpoint on TMDb's docs. The method here:

https://github.com/LordMike/TMDbLib/blob/049fba9f720acf21534ae8d2f4dca7a375586cb8/TMDbLib/Client/TMDbClientJobs.cs#L16-L23

calls in to `jobs/list` - but that endpoint doesn't exist on https://developers.themoviedb.org/3/

**Comment by FrederikBolding** [comment]
It's this one right?

https://developers.themoviedb.org/3/configuration/get-jobs-1

**Comment by FrederikBolding** [comment]
@LordMike I just tried it with `configuration/job` which returns almost the same. You want to use that endpoint instead?

**Comment by LordMike** [comment]
Does `jobs/list` exist?

Do you have two example outputs?

**Comment by FrederikBolding** [comment]
I can't find it in the documentation either, but it works.

Here is `job/list`:
```json

{"jobs":[{"department":"Crew","jobs":["Special Effects","Post Production Supervisor","Second Unit","Choreographer","Stunts","Stunt Coordinator","Special Effects Coordinator","Supervising Technical Director","Supervising Animator","Production Artist","Sequence Leads","Second Film Editor","Temp Music Editor","Temp Sound Editor","Sequence Supervisor","Software Team Lead","Software Engineer","Documentation & Support","Machinist","Photoscience Manager","Department Administrator","Schedule Coordinator","Supervisor of Production Resources","Production Office Assistant","Information Systems Manager","Systems Administrators & Support","Projection","Post Production Assistant","Sound Design Assistant","Mix Technician","Motion Actor","Sets & Props Supervisor","Compositors","Tattooist","Sets & Props Artist","Motion Capture Artist","Sequence Artist","Mixing Engineer","Special Sound Effects","Post-Production Manager","Dialect Coach","Picture Car Coordinator","Cableman","Set Production Assistant","Video Assist Operator","Unit Publicist","Set Medic","Stand In","Transportation Coordinator","Transportation Captain","Post Production Consulting","Production Intern","Utility Stunts","Actor's Assistant","Set Production Intern","Production Controller","Studio Teachers","Chef","Craft Service","Scenic Artist","Propmaker","Prop Maker","Transportation Co-Captain","Driver","Security","Second Unit Cinematographer","Loader","Manager of Operations","Quality Control Supervisor","Legal Services","Public Relations","Score Engineer","Translator","Title Graphics","Telecine Colorist","Animatronic and Prosthetic Effects","Martial Arts Choreographer","Cinematography","Steadycam","Executive Visual Effects Producer","Visual Effects Design Consultant","Digital Effects Supervisor","Digital Producer","CG Supervisor","Visual Effects Art Director","Visual Effects Editor","Executive in Charge of Finance","Associate Choreographer","Makeup Effects","Treatment","Dramaturgy","Lighting Camera","Technical Supervisor","CGI Supervisor","Creative Consultant","Script","Executive Music Producer","Commissioning Editor","Additional Writing","Additional Music","Poem","Thanks","Creator","Additional Dialogue","Video Game","Graphic Novel Illustrator","Other","Series Writer","Radio Play","Armorer","Carpenter","Editorial Staff","Aerial Coordinator","Animal Coordinator","Animal Wrangler","Animatronics Designer","Drone Operator","In Memory Of","Pilot","Presenter","Animatronics Supervisor","Armory Coordinator","Digital Effects Producer","Fight Choreographer","Marine Coordinator","Pyrotechnician","Techno Crane Operator"]},{"department":"Sound","jobs":["Original Music Composer","Sound Designer","Sound Editor","Sound Director","Sound Mixer","Music Editor","Sound Effects Editor","Production Sound Mixer","Additional Soundtrack","Supervising Sound Editor","Supervising Sound Effects Editor","Sound Re-Recording Mixer","Recording Supervision","Boom Operator","Sound Montage Associate","Songs","Music","ADR & Dubbing","Sound Recordist","Sound Engineer","Foley","Dialogue Editor","Additional Music Supervisor","First Assistant Sound Editor","Scoring Mixer","Dolby Consultant","Other","Music Director","Orchestrator","Vocal Coach","Music Supervisor","Sound","Musician","Additional Sound Re-Recording Mixer","Additional Sound Re-Recordist","ADR Editor","ADR Supervisor","Apprentice Sound Editor","Assistant Music Supervisor","Assistant Sound Editor","Conductor","Foley Editor","Music Programmer","Music Score Producer","Playback Singer","Sound Effects","Sound Effects Designer","Supervising ADR Editor","Supervising Dialogue Editor","Supervising Music Editor","Theme Song Performance","Utility Sound"]},{"department":"Lighting","jobs":["Lighting Technician","Best Boy Electric","Gaffer","Rigging Gaffer","Lighting Supervisor","Lighting Manager","Directing Lighting Artist","Master Lighting Artist","Lighting Artist","Lighting Coordinator","Lighting Production Assistant","Best Boy Electrician","Electrician","Rigging Grip","Other","Chief Lighting Technician","Lighting Director","Rigging Supervisor","Underwater Gaffer"]},{"department":"Production","jobs":["Producer","Executive Producer","Casting","Production Manager","Unit Production Manager","Line Producer","Location Manager","Other","Production Supervisor","Production Accountant","Production Office Coordinator","Finance","Executive Consultant","Character Technical Supervisor","Development Manager","Administration","Executive In Charge Of Post Production","Production Director","Executive In Charge Of Production","Publicist","Associate Producer","Co-Producer","Co-Executive Producer","Casting Associate","Researcher","Production Coordinator","Consulting Producer","Supervising Producer","Senior Executive Consultant","Unit Manager","ADR Voice Casting","Assistant Production Coordinator","Assistant Production Manager","Casting Assistant","Casting Consultant","Coordinating Producer","Local Casting","Script Researcher"]},{"department":"Art","jobs":["Production Design","Art Direction","Set Decoration","Set Designer","Conceptual Design","Interior Designer","Settings","Assistant Art Director","Art Department Coordinator","Assistant Property Master","Other","Art Department Manager","Sculptor","Art Department Assistant","Background Designer","Co-Art Director","Set Decoration Buyer","Production Illustrator","Standby Painter","Property Master","Location Scout","Supervising Art Director","Leadman","Greensman","Gun Wrangler","Construction Coordinator","Construction Foreman","Lead Painter","Sign Painter","Painter","Assistant Set Dresser","Conceptual Illustrator","Draughtsman","Lead Set Dresser","Prop Designer","Set Decorating Coordinator","Set Dresser","Storyboard Designer","Title Designer"]},{"department":"Editing","jobs":["Editor","Supervising Film Editor","Additional Editing","Editorial Manager","First Assistant Editor","Additional Editorial Assistant","Editorial Coordinator","Editorial Production Assistant","Editorial Services","Archival Footage Coordinator","Archival Footage Research","Color Timer","Digital Intermediate","Other","Assistant Editor","Associate Editor","Co-Editor","Negative Cutter"]},{"department":"Costume & Make-Up","jobs":["Costume Design","Makeup Artist","Hairstylist","Set Dressing Artist","Set Dressing Supervisor","Set Dressing Manager","Set Dressing Production Assistant","Facial Setup Artist","Hair Setup","Costume Supervisor","Set Costumer","Makeup Department Head","Wigmaker","Shoe Design","Other","Co-Costume Designer","Hair Department Head","Hair Designer","Makeup Designer","Assistant Costume Designer","Prosthetic Supervisor","Seamstress","Key Hair Stylist","Ager/Dyer","Costume Consultant","Costume Coordinator","Costume Illustrator","Hair Supervisor","Key Costumer","Key Makeup Artist","Key Set Costumer","Makeup Effects Designer","Makeup Supervisor","Prosthetic Designer","Prosthetic Makeup Artist","Tailor","Tattoo Designer","Wardrobe Supervisor","Wig Designer"]},{"department":"Camera","jobs":["Director of Photography","Underwater Camera","Camera Operator","Still Photographer","Camera Department Manager","Camera Supervisor","Camera Technician","Other","Grip","Steadicam Operator","Additional Camera","Camera Intern","Additional Photography","Helicopter Camera","First Assistant Camera","Additional Still Photographer","Aerial Camera","Aerial Camera Technician","Aerial Director of Photography","Camera Loader","Dolly Grip","Epk Camera Operator","Key Grip","Russian Arm Operator","Second Unit Director of Photography","Ultimate Arm Operator","Underwater Director of Photography"]},{"department":"Directing","jobs":["Director","Script Supervisor","Other","Layout","Script Coordinator","Special Guest Director","Assistant Director","Co-Director","Continuity","First Assistant Director","Second Assistant Director","Third Assistant Director"]},{"department":"Visual Effects","jobs":["Animation","Visual Effects","Chief Technician / Stop-Motion Expert","Creature Design","Shading","Modeling","CG Painter","Visual Development","Animation Manager","Animation Director","Fix Animator","Animation Department Coordinator","Animation Fix Coordinator","Animation Production Assistant","Visual Effects Supervisor","Mechanical & Creature Designer","Battle Motion Coordinator","Animation Supervisor","VFX Supervisor","Cloth Setup","VFX Artist","CG Engineer","24 Frame Playback","Imaging Science","I/O Supervisor","Visual Effects Producer","VFX Production Coordinator","I/O Manager","Additional Effects Development","Color Designer","Simulation & Effects Production Assistant","Simulation & Effects Artist","Pyrotechnic Supervisor","Special Effects Supervisor","3D Supervisor","3D Director","Digital Compositors","Visual Effects Coordinator","VFX Editor","2D Artist","2D Supervisor","3D Animator","3D Artist","3D Coordinator","3D Generalist","3D Modeller","3D Sequence Supervisor","3D Tracking Layout","CG Animator","CGI Director","Character Designer","Character Modelling Supervisor","Creature Technical Director","Digital Effects Producer","Key Animation","Lead Animator","Lead Character Designer","Matchmove Supervisor","Mechanical Designer","Opening/Ending Animation","Pre-Visualization Supervisor","Roto Supervisor","Stereoscopic Coordinator","VFX Director of Photography","VFX Lighting Artist","Visual Effects Designer","Visual Effects Technical Director"]},{"department":"Actors","jobs":["Actor","Stunt Double","Voice","Cameo","Special Guest"]},{"department":"Writing","jobs":["Screenplay","Author","Novel","Characters","Theatre Play","Adaptation","Dialogue","Writer","Other","Storyboard","Original Story","Scenario Writer","Screenstory","Musical","Idea","Story","Creative Producer","Teleplay","Opera","Co-Writer","Book","Comic Book","Short Story","Series Composition","Script Editor","Script Consultant","Story Editor"]}]}
```

And here is `configuration/jobs`:
```json

[{"department":"Crew","jobs":["Special Effects","Post Production Supervisor","Second Unit","Choreographer","Stunts","Stunt Coordinator","Special Effects Coordinator","Supervising Technical Director","Supervising Animator","Production Artist","Sequence Leads","Second Film Editor","Temp Music Editor","Temp Sound Editor","Sequence Supervisor","Software Team Lead","Software Engineer","Documentation & Support","Machinist","Photoscience Manager","Department Administrator","Schedule Coordinator","Supervisor of Production Resources","Production Office Assistant","Information Systems Manager","Systems Administrators & Support","Projection","Post Production Assistant","Sound Design Assistant","Mix Technician","Motion Actor","Sets & Props Supervisor","Compositors","Tattooist","Sets & Props Artist","Motion Capture Artist","Sequence Artist","Mixing Engineer","Special Sound Effects","Post-Production Manager","Dialect Coach","Picture Car Coordinator","Cableman","Set Production Assistant","Video Assist Operator","Unit Publicist","Set Medic","Stand In","Transportation Coordinator","Transportation Captain","Post Production Consulting","Production Intern","Utility Stunts","Actor's Assistant","Set Production Intern","Production Controller","Studio Teachers","Chef","Craft Service","Scenic Artist","Propmaker","Prop Maker","Transportation Co-Captain","Driver","Security","Second Unit Cinematographer","Loader","Manager of Operations","Quality Control Supervisor","Legal Services","Public Relations","Score Engineer","Translator","Title Graphics","Telecine Colorist","Animatronic and Prosthetic Effects","Martial Arts Choreographer","Cinematography","Steadycam","Executive Visual Effects Producer","Visual Effects Design Consultant","Digital Effects Supervisor","Digital Producer","CG Supervisor","Visual Effects Art Director","Visual Effects Editor","Executive in Charge of Finance","Associate Choreographer","Makeup Effects","Treatment","Dramaturgy","Lighting Camera","Technical Supervisor","CGI Supervisor","Creative Consultant","Script","Executive Music Producer","Commissioning Editor","Additional Writing","Additional Music","Poem","Thanks","Creator","Additional Dialogue","Video Game","Graphic Novel Illustrator","Other","Series Writer","Radio Play","Armorer","Carpenter","Editorial Staff","Aerial Coordinator","Animal Coordinator","Animal Wrangler","Animatronics Designer","Drone Operator","In Memory Of","Pilot","Presenter","Animatronics Supervisor","Armory Coordinator","Digital Effects Producer","Fight Choreographer","Marine Coordinator","Pyrotechnician","Techno Crane Operator"]},{"department":"Sound","jobs":["Original Music Composer","Sound Designer","Sound Editor","Sound Director","Sound Mixer","Music Editor","Sound Effects Editor","Production Sound Mixer","Additional Soundtrack","Supervising Sound Editor","Supervising Sound Effects Editor","Sound Re-Recording Mixer","Recording Supervision","Boom Operator","Sound Montage Associate","Songs","Music","ADR & Dubbing","Sound Recordist","Sound Engineer","Foley","Dialogue Editor","Additional Music Supervisor","First Assistant Sound Editor","Scoring Mixer","Dolby Consultant","Other","Music Director","Orchestrator","Vocal Coach","Music Supervisor","Sound","Musician","Additional Sound Re-Recording Mixer","Additional Sound Re-Recordist","ADR Editor","ADR Supervisor","Apprentice Sound Editor","Assistant Music Supervisor","Assistant Sound Editor","Conductor","Foley Editor","Music Programmer","Music Score Producer","Playback Singer","Sound Effects","Sound Effects Designer","Supervising ADR Editor","Supervising Dialogue Editor","Supervising Music Editor","Theme Song Performance","Utility Sound"]},{"department":"Lighting","jobs":["Lighting Technician","Best Boy Electric","Gaffer","Rigging Gaffer","Lighting Supervisor","Lighting Manager","Directing Lighting Artist","Master Lighting Artist","Lighting Artist","Lighting Coordinator","Lighting Production Assistant","Best Boy Electrician","Electrician","Rigging Grip","Other","Chief Lighting Technician","Lighting Director","Rigging Supervisor","Underwater Gaffer"]},{"department":"Production","jobs":["Producer","Executive Producer","Casting","Production Manager","Unit Production Manager","Line Producer","Location Manager","Other","Production Supervisor","Production Accountant","Production Office Coordinator","Finance","Executive Consultant","Character Technical Supervisor","Development Manager","Administration","Executive In Charge Of Post Production","Production Director","Executive In Charge Of Production","Publicist","Associate Producer","Co-Producer","Co-Executive Producer","Casting Associate","Researcher","Production Coordinator","Consulting Producer","Supervising Producer","Senior Executive Consultant","Unit Manager","ADR Voice Casting","Assistant Production Coordinator","Assistant Production Manager","Casting Assistant","Casting Consultant","Coordinating Producer","Local Casting","Script Researcher"]},{"department":"Art","jobs":["Production Design","Art Direction","Set Decoration","Set Designer","Conceptual Design","Interior Designer","Settings","Assistant Art Director","Art Department Coordinator","Assistant Property Master","Other","Art Department Manager","Sculptor","Art Department Assistant","Background Designer","Co-Art Director","Set Decoration Buyer","Production Illustrator","Standby Painter","Property Master","Location Scout","Supervising Art Director","Leadman","Greensman","Gun Wrangler","Construction Coordinator","Construction Foreman","Lead Painter","Sign Painter","Painter","Assistant Set Dresser","Conceptual Illustrator","Draughtsman","Lead Set Dresser","Prop Designer","Set Decorating Coordinator","Set Dresser","Storyboard Designer","Title Designer"]},{"department":"Editing","jobs":["Editor","Supervising Film Editor","Additional Editing","Editorial Manager","First Assistant Editor","Additional Editorial Assistant","Editorial Coordinator","Editorial Production Assistant","Editorial Services","Archival Footage Coordinator","Archival Footage Research","Color Timer","Digital Intermediate","Other","Assistant Editor","Associate Editor","Co-Editor","Negative Cutter"]},{"department":"Costume & Make-Up","jobs":["Costume Design","Makeup Artist","Hairstylist","Set Dressing Artist","Set Dressing Supervisor","Set Dressing Manager","Set Dressing Production Assistant","Facial Setup Artist","Hair Setup","Costume Supervisor","Set Costumer","Makeup Department Head","Wigmaker","Shoe Design","Other","Co-Costume Designer","Hair Department Head","Hair Designer","Makeup Designer","Assistant Costume Designer","Prosthetic Supervisor","Seamstress","Key Hair Stylist","Ager/Dyer","Costume Consultant","Costume Coordinator","Costume Illustrator","Hair Supervisor","Key Costumer","Key Makeup Artist","Key Set Costumer","Makeup Effects Designer","Makeup Supervisor","Prosthetic Designer","Prosthetic Makeup Artist","Tailor","Tattoo Designer","Wardrobe Supervisor","Wig Designer"]},{"department":"Camera","jobs":["Director of Photography","Underwater Camera","Camera Operator","Still Photographer","Camera Department Manager","Camera Supervisor","Camera Technician","Other","Grip","Steadicam Operator","Additional Camera","Camera Intern","Additional Photography","Helicopter Camera","First Assistant Camera","Additional Still Photographer","Aerial Camera","Aerial Camera Technician","Aerial Director of Photography","Camera Loader","Dolly Grip","Epk Camera Operator","Key Grip","Russian Arm Operator","Second Unit Director of Photography","Ultimate Arm Operator","Underwater Director of Photography"]},{"department":"Directing","jobs":["Director","Script Supervisor","Other","Layout","Script Coordinator","Special Guest Director","Assistant Director","Co-Director","Continuity","First Assistant Director","Second Assistant Director","Third Assistant Director"]},{"department":"Visual Effects","jobs":["Animation","Visual Effects","Chief Technician / Stop-Motion Expert","Creature Design","Shading","Modeling","CG Painter","Visual Development","Animation Manager","Animation Director","Fix Animator","Animation Department Coordinator","Animation Fix Coordinator","Animation Production Assistant","Visual Effects Supervisor","Mechanical & Creature Designer","Battle Motion Coordinator","Animation Supervisor","VFX Supervisor","Cloth Setup","VFX Artist","CG Engineer","24 Frame Playback","Imaging Science","I/O Supervisor","Visual Effects Producer","VFX Production Coordinator","I/O Manager","Additional Effects Development","Color Designer","Simulation & Effects Production Assistant","Simulation & Effects Artist","Pyrotechnic Supervisor","Special Effects Supervisor","3D Supervisor","3D Director","Digital Compositors","Visual Effects Coordinator","VFX Editor","2D Artist","2D Supervisor","3D Animator","3D Artist","3D Coordinator","3D Generalist","3D Modeller","3D Sequence Supervisor","3D Tracking Layout","CG Animator","CGI Director","Character Designer","Character Modelling Supervisor","Creature Technical Director","Digital Effects Producer","Key Animation","Lead Animator","Lead Character Designer","Matchmove Supervisor","Mechanical Designer","Opening/Ending Animation","Pre-Visualization Supervisor","Roto Supervisor","Stereoscopic Coordinator","VFX Director of Photography","VFX Lighting Artist","Visual Effects Designer","Visual Effects Technical Director"]},{"department":"Actors","jobs":["Actor","Stunt Double","Voice","Cameo","Special Guest"]},{"department":"Writing","jobs":["Screenplay","Author","Novel","Characters","Theatre Play","Adaptation","Dialogue","Writer","Other","Storyboard","Original Story","Scenario Writer","Screenstory","Musical","Idea","Story","Creative Producer","Teleplay","Opera","Co-Writer","Book","Comic Book","Short Story","Series Composition","Script Editor","Script Consultant","Story Editor"]}]
```

The only difference I can spot is that `configuration/jobs` is just an array while `job/list` returns an object that contains the array.

**Comment by LordMike** [comment]
Just had a chance. Amazing this has gone unnoticed (but then again, I might have overcomplicated the tests ...)

**Comment by FrederikBolding** [comment]
Come to think of it, wouldn't it be in our best interest to use the documented function instead? @LordMike

**Comment by LordMike** [comment]
It would. This was just fixing the immediate bug, implementing `/Configuration` fully is better.

**Comment by FrederikBolding** [comment]
Pushed to code to PR #255

**Pull request merged**
