### PR TITLE
fixed: missing "Request Rate Limiting" handling

### PR DESCRIPTION
**Pull request by DanCooper**
handle TMDB request rate limit (error 429)

### CODE REVIEW

**Comment by Naliath** [comment]
Not sure I agree with this implementation. While it might 'work' there is already a retry mechanic available on the rest client itself. Status 429 mean that it will simply not work for x seconds => 
>Right now when you actually trip the rate limits, we just throw a 503 error which is really not the right way to do this. Moving forward, we'll be throwing a proper 429 status code along with a Retry-After header telling you how many seconds to wait until you're allowed to make a request again
>TMDb https://www.themoviedb.org/talk/5317af69c3a3685c4a0003b1?page=1

As indicated in this discussion: https://github.com/LordMike/TMDbLib/issues/38 we should add a property to indicate if we need to just keep waiting or throw an error so the application can deal with it.

**Comment by DanCooper** [comment]
I have read that discussion.

My problem is that TMDBLib does not tell me that in any way. My software (Ember Media Manager) runs very often in that TMDB limit. It looks like TMDBLib does not wait or throw an error.
In this situation TMDBLib gives back a Movie, but the client values like Client.Images.BaseURL is NULL. This is not consistent.

**Comment by DanCooper** [comment]
... and my solution does wait if you have set the MaxRetryCount to > 0.

**Comment by Naliath** [comment]
Correct, I'll try and have a fix up tonight that would throw a custom error that tell you this, or will retry the call after the indicated time has expired (I think I'll make that the default if @LordMike agrees).

**Comment by Naliath** [comment]
https://github.com/LordMike/TMDbLib/commit/ea8c2e1603fd98baa6bd887fe01405bcd884c094

**Pull request closed without merging**
