### PR TITLE
Added the origin country to the company.

### PR DESCRIPTION
**Pull request by lukasroegner**
Companies have a two-letter country code of the origin country of the companies.

### CODE REVIEW

**Comment by FrederikBolding** [comment]
I think that could be a good idea, as we've had a few changes lately. We'll see when he responds 😄

**Comment by LordMike** [comment]
Looks good.

**Comment by LordMike** [comment]
@lukasroegner see 1.3.1-alpha

**Comment by lukasroegner** [comment]
@LordMike Thank you so much for your work!

**Pull request merged**
