### PR TITLE
Add cancellation-tokens to async methods

### LINKED ISSUE #231: Async Functions with overload CancellationToken passed?
Any chance a future version will be able to take a CancellationToken on the Async ops?  This way if a user is waiting on an operation, and they want to cancel it, it will stop it? I know it returns a Task<Type> on those functions, and you are leaning on the .Result for many of the functions.  This way you can pass the token all the way down the stack. Following your source, it seems like it could be easily passed. You could add the optional param.

I know this is opensource, so I guess I could add it if desired.  What is your thought on that?

Cool Lib BTW.

### PR DESCRIPTION
**Pull request by LordMike**
Closes #231

### CODE REVIEW

**Comment by LordMike** [comment]
@twhidden how does this look?

**Comment by LordMike** [comment]
Note: This change is breaking the API surface. The new DLL will not be a drop-in replacement, users have to recompile to get the new method definitions.

**Comment by TWhidden** [comment]
Not necessarily. The token can have a default value param, the compiler won't break existing API usages. When I get back to my PC, I'll branch and mock.

**Comment by LordMike** [comment]
It will. For most cases, sure, a recompile will handle it - but for cases with existing compiled programs that reference TMDbLib, it'll be breaking, as the old methods no longer exist. 

Anyways. It's a non-issue, as I won't maintain overload methods just to support a rare case of usage :).

**Pull request merged**
