### PR TITLE
Rewrite of the Discover methods

### PR DESCRIPTION
**Pull request by LordMike**
Issue #95

### CODE REVIEW

**Comment by LordMike** [comment]
@Naliath what's your thought on this way of doing it?

My thought was that we couldn't keep adding parameters.

**Comment by Naliath** [comment]
Not sure how else to do this, while it might get a bit large this seems like an easy way to use the interface.

**Comment by LordMike** [comment]
At least its extensible. We could also make a StartQuery, which returns an object that has all these methods. It then has a Query method which will do the actual query.

That way, we can keep it more fluent.

Eg.
Client.DiscoverTv().InYear(2015).Query().

**Comment by Naliath** [comment]
sounds good, I like functional programming :)

**Comment by LordMike** [comment]
So the question is if this is a better approach than the one I've created
just now.

Mvh.
Michael

**Comment by LordMike** [comment]
Also, I'd call it fluent programming - not functional ;)

Mvh.
Michael

**Pull request merged**
