### PR TITLE
Added a bunch of missing variables and fixed some tests

### PR DESCRIPTION
**Pull request by FrederikBolding**

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Hmm, just realized Gender is only available Find and not Search.

**Comment by FrederikBolding** [comment]
There is still some tests to be fixed, should I just ignore missing "gender" variable on some tests? Just like we do on other objects that don't return the exact object defined in C#? @LordMike

**Comment by FrederikBolding** [comment]
So an `FindPerson` that inherits from `SearchPerson` and adds `Gender` maybe?

**Comment by FrederikBolding** [comment]
Gender for Finding should be working find now, I added `KnownForDepartment `to the `FindPerson `object as well. Genders are still behaving a bit weirdly with regards to `CreatedBy` (#260)

**Comment by LordMike** [comment]
Did you solve the issues with `Gender`?

**Comment by FrederikBolding** [comment]
However, it shouldn't be much of an issue as the library handles the inconsistencies fine.

**Pull request merged**
