### PR TITLE
Updated TranslationData model

### PR DESCRIPTION
**Pull request by Almis90**
Replaced name with title
Added runtime

### CODE REVIEW

**Comment by Almis90** [comment]
This is an urgent pull request because right now I cannot get the translated titles.

**Comment by LordMike** [comment]
Ah, so I see that Movie and Tv have different translation datas, your change will break it for movies, which still use "title" - while Tv will use "name".

**Comment by LordMike** [comment]
@Almis90 could you try out this branch on the tv show you're looking at?
It should fill out `Name` with the `title` from the response

**Comment by LordMike** [comment]
Also - I can't identify any translation datas with "runtime" in them, can you confirm its a property that exists somewhere?

**Comment by Almis90** [comment]
Check this url https://api.themoviedb.org/3/movie/818397/translations?api_key={api_key}

**Comment by Almis90** [comment]
> @Almis90 could you try out this branch on the tv show you're looking at?
> It should fill out `Name` with the `title` from the response

Yes, it's working, but I tested only movies not tv-shows, the hack worked :)

**Comment by Almis90** [comment]
> Check this url [https://api.themoviedb.org/3/movie/818397/translations?api_key={api_key}](https://api.themoviedb.org/3/movie/818397/translations?api_key=%7Bapi_key%7D)

I did check the result in above url

**Comment by vindberg** [comment]
Hi, good work. When will this be commited in the master? @LordMike can you push it out as a nuget also? 

Thanks.

**Comment by LordMike** [comment]
I'll try to see if I can push this. In the meantime, you should be able to use the package registry in this Github repo - all CI builds should end up there.

Mike.
________________________________

**Comment by vindberg** [comment]
Thanks.

Im not able to find a nuget package from the fork or in the Actions section... so hoping this can be pushed out :)

**Comment by LordMike** [comment]
https://github.com/LordMike/TMDbLib/packages/691970

I made a short post on consuming it here:
https://blog.mbwarez.dk/consuming-my-nuget-packages-from-github/

**Comment by LordMike** [comment]
Ooh - sorry, I completely missed that this is a PR - I was looking at mails and thought it was an issue.

**Comment by LordMike** [comment]
A new package should arrive at the feed I linked at, shortly.. :)

**Comment by vindberg** [comment]
Thanks, appreciate it.

**Pull request merged**
